%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/xiang/dataset/rgbd_dataset_freiburg1_desk

# camera intrinsics
# fr1
camera.fx:  576.136966392455 #阿波罗数据
camera.fy:  576.4689170155
camera.cx:  423.0
camera.cy:  339.0

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 1000

# VO Parameters
number_of_features: 2000
scale_factor: 1.25
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 5
min_inliers: 15
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
max_depth: 150.0
